Listen = "0.0.0.0:9001"
DataDir = "./data"
Debug = true
ProxyURL = "http://172.22.11.47:7777"
CallbackToken = "e8hgcjp4fsn6kq1pbe6hkgkvf89svvbi"

[MidJourneyConfig]
  Enabled = true
  UserToken = "NTQ5OTU3MDc5NTExNTk3MDY3.GiDQm3.PoUBk0SXPob1BZ6ovPaGaQYN8kTKzbAiHKx7Mo"
  BotToken = "MTEzODcxNjA4MjQ0NjgxMTIxNg.GhiYta.-BeimJrJITPMpLH4QliiRxDC3bzkLvtpryFGJg"
  GuildId = "1138713254718361630"
  ChanelId = "1138713254718361633"
  CallbackUrl = "http://172.22.11.47:5678/api/mj/notify"

[WeChatConfig]
  Enabled = false
  CallbackUrl = "http://172.22.11.47:5678/api/reward/notify"

[RedisConfig]
  Address = "172.22.11.47:6379"
  Password = ""
  Db = 0
