version: '3'
services:
  chatgpt-plus-exts:
    image: registry.cn-hangzhou.aliyuncs.com/geekmaster/chatgpt-plus-exts:v3.0.7
    container_name: chatgpt-plus-exts
    restart: always
    environment:
      - CONFIG_FILE=config.toml

    ports:
      - "9010:9010"
    volumes:
      - ./data:/var/www/app/data
      - ./config.toml:/var/www/app/config.toml
      - ./logs/api:/var/www/app/logs
